#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
# Source0 file verified with key 0x13FCEF89DD9E3C4F (nickc@redhat.com)
#
Name     : binutils
Version  : 2.41
Release  : 521
URL      : https://mirrors.kernel.org/gnu/binutils/binutils-2.41.tar.xz
Source0  : https://mirrors.kernel.org/gnu/binutils/binutils-2.41.tar.xz
Source1  : https://mirrors.kernel.org/gnu/binutils/binutils-2.41.tar.xz.sig
Summary  : zlib compression library
Group    : Development/Tools
License  : BSL-1.0 GPL-2.0 GPL-3.0 GPL-3.0+ LGPL-2.0 LGPL-2.1 LGPL-3.0
BuildRequires : bison
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : flex
BuildRequires : glibc-staticdev
BuildRequires : help2man
BuildRequires : lz4-dev
BuildRequires : lzo-dev
BuildRequires : pypi(msgpack)
BuildRequires : texinfo
BuildRequires : xz-dev
BuildRequires : zlib-dev
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: binutils-stable-branch.patch
Patch2: binutils-add-LD_AS_NEEDED-global-env.patch
Patch3: compilespeed.patch
Patch4: zlib-level.patch

%description
This directory contains various GNU compilers, assemblers, linkers,
debuggers, etc., plus their support routines, definitions, and documentation.

%prep
%setup -q -n binutils-2.41
cd %{_builddir}/binutils-2.41
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
pushd ..
cp -a binutils-2.41 buildavx2
popd

%build
## build_prepend content
rm -rf gdb libdecnumber readline sim
export SOURCE_DATE_EPOCH=1549215809
sed -i -e "s/#define BFD_VERSION_DATE.*/#define BFD_VERSION_DATE 20190203/g" bfd/version.h

# Force all man pages to regenerate... they were truncated in the 2.37 release
touch binutils/doc/binutils.texi
touch gas/doc/as.texi
touch gprof/gprof.texi
touch ld/ld.texi


# relro costs quite a bit for compile time
export CFLAGS="$CFLAGS -Wl,-z,norelro  -g1 -gno-column-info -gno-variable-location-views -gz"
export CXXFLAGS="$CXXFLAGS -Wl,-z,norelro  -g1 -gno-column-info -gno-variable-location-views -gz"

# Do not use a macro - breaks toolchain
./configure \
--prefix=/usr \
--libdir=/usr/lib64 \
--includedir=/usr/include \
--with-lib-path=/usr/lib64:/usr/lib32:/usr/lib \
--enable-shared --disable-static \
--target=x86_64-generic-linux \
--build=x86_64-generic-linux \
--enable-targets=all \
--enable-deterministic-archives \
--enable-lto \
--enable-plugins \
--enable-gold \
--enable-secureplt \
--disable-werror \
--enable-64-bit-bfd \
--with-system-zlib \
--without-debuginfod
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1690822732
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}  -O tooldir=/usr

pushd ../buildavx2
## build_prepend content
rm -rf gdb libdecnumber readline sim
export SOURCE_DATE_EPOCH=1549215809
sed -i -e "s/#define BFD_VERSION_DATE.*/#define BFD_VERSION_DATE 20190203/g" bfd/version.h

# Force all man pages to regenerate... they were truncated in the 2.37 release
touch binutils/doc/binutils.texi
touch gas/doc/as.texi
touch gprof/gprof.texi
touch ld/ld.texi


# relro costs quite a bit for compile time
export CFLAGS="$CFLAGS -Wl,-z,norelro  -g1 -gno-column-info -gno-variable-location-views -gz"
export CXXFLAGS="$CXXFLAGS -Wl,-z,norelro  -g1 -gno-column-info -gno-variable-location-views -gz"

# Do not use a macro - breaks toolchain
./configure \
--prefix=/usr \
--libdir=/usr/lib64 \
--includedir=/usr/include \
--with-lib-path=/usr/lib64:/usr/lib32:/usr/lib \
--enable-shared --disable-static \
--target=x86_64-generic-linux \
--build=x86_64-generic-linux \
--enable-targets=all \
--enable-deterministic-archives \
--enable-lto \
--enable-plugins \
--enable-gold \
--enable-secureplt \
--disable-werror \
--enable-64-bit-bfd \
--with-system-zlib \
--without-debuginfod
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
make  %{?_smp_mflags}  -O tooldir=/usr
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_flags} -O check tooldir=/usr || :

%install
export SOURCE_DATE_EPOCH=1690822732
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/binutils
cp %{_builddir}/binutils-%{version}/COPYING %{buildroot}/usr/share/package-licenses/binutils/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
cp %{_builddir}/binutils-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/binutils/0e8e850b0580fbaaa0872326cb1b8ad6adda9b0d || :
cp %{_builddir}/binutils-%{version}/COPYING3 %{buildroot}/usr/share/package-licenses/binutils/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/binutils-%{version}/COPYING3.LIB %{buildroot}/usr/share/package-licenses/binutils/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/binutils-%{version}/bfd/COPYING %{buildroot}/usr/share/package-licenses/binutils/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/binutils-%{version}/gas/COPYING %{buildroot}/usr/share/package-licenses/binutils/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/binutils-%{version}/include/COPYING %{buildroot}/usr/share/package-licenses/binutils/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
cp %{_builddir}/binutils-%{version}/include/COPYING3 %{buildroot}/usr/share/package-licenses/binutils/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/binutils-%{version}/libiberty/COPYING.LIB %{buildroot}/usr/share/package-licenses/binutils/597bf5f9c0904bd6c48ac3a3527685818d11246d || :
cp %{_builddir}/binutils-%{version}/zlib/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/binutils/892b34f7865d90a6f949f50d95e49625a10bc7f0 || :
pushd ../buildavx2/
%make_install_v3 tooldir=/usr
popd
%make_install tooldir=/usr
## Remove excluded files
rm -f %{buildroot}*/usr/bin/dlltool
rm -f %{buildroot}*/usr/bin/windres
rm -f %{buildroot}*/usr/lib/ldscripts/i386pe.x
rm -f %{buildroot}*/usr/lib/ldscripts/i386pe.xa
rm -f %{buildroot}*/usr/lib/ldscripts/i386pe.xbn
rm -f %{buildroot}*/usr/lib/ldscripts/i386pe.xe
rm -f %{buildroot}*/usr/lib/ldscripts/i386pe.xn
rm -f %{buildroot}*/usr/lib/ldscripts/i386pe.xr
rm -f %{buildroot}*/usr/lib/ldscripts/i386pe.xu
rm -f %{buildroot}*/usr/lib/ldscripts/i386pep.x
rm -f %{buildroot}*/usr/lib/ldscripts/i386pep.xa
rm -f %{buildroot}*/usr/lib/ldscripts/i386pep.xbn
rm -f %{buildroot}*/usr/lib/ldscripts/i386pep.xe
rm -f %{buildroot}*/usr/lib/ldscripts/i386pep.xn
rm -f %{buildroot}*/usr/lib/ldscripts/i386pep.xr
rm -f %{buildroot}*/usr/lib/ldscripts/i386pep.xu
rm -f %{buildroot}*/usr/etc/gprofng.rc
## install_append content
install -d %{buildroot}/usr/include

# Manually install libiberty - can be fixed post glibc/gcc fixups
install -m 0644 libiberty/libiberty.a %{buildroot}/usr/lib64

# Find out who is using these headers and reduce their usage.
install -m 644 include/ansidecl.h %{buildroot}/usr/include/
install -m 644 include/libiberty.h %{buildroot}/usr/include/
install -m 644 include/plugin-api.h %{buildroot}/usr/include/

install -d %{buildroot}/usr/include/libiberty
install -m 644 include/*.h %{buildroot}/usr/include/libiberty/

install -d %{buildroot}/usr/lib64/gcc/x86_64-generic-linux/12/
cp -a %{buildroot}/usr/bin/as %{buildroot}/usr/lib64/gcc/x86_64-generic-linux/12/as
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
