update:
	test -d ~/git/binutils-gdb || git clone https://sourceware.org/git/binutils-gdb.git ~/git/binutils-gdb
	( \
		cd ~/git/binutils-gdb ; \
		git remote update -p > /dev/null 2>&1 ; \
		git diff binutils-2_36..origin/binutils-2_36-branch | filterdiff --exclude="*/bfd/version.h"; \
	) > binutils-stable-branch.patch
	git diff --exit-code binutils-stable-branch.patch || bash ./update.sh
